#!/usr/bin/python3

from sys import *
from os import listdir
from os.path import isfile, join
from itertools import chain

listofimports = ['SBT', 'JetBrains']

if len(argv) > 1:
    listofimports += list(chain(*map(lambda x: x.split(':'), argv[1:])))

finalname = 'ignore2'

finalfile = open(finalname, 'w+')

for i in listofimports:
    f = open(join('.', 'gitignore/Global', i + '.gitignore'))
    for line in f.readlines():
        finalfile.write(line)
    finalfile.write('\n\n')





    

